# Generated by Django 2.2.5 on 2020-10-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_pre', models.TextField()),
                ('link_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data')),
            ],
            options={
                'db_table': 'preprocessing',
            },
        ),
    ]
