# Generated by Django 2.2.5 on 2020-10-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_idf_dict', models.DecimalField(decimal_places=4, max_digits=19)),
                ('id_pre_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Preprocessing')),
            ],
            options={
                'db_table': 'klasifikasi',
            },
        ),
    ]
