# Generated by Django 3.0.8 on 2021-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0002_auto_20201021_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasi',
            name='tf_idf_dict',
            field=models.TextField(),
        ),
    ]
