# Generated by Django 3.0.8 on 2021-01-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
        ('klasifikasi', '0003_auto_20210103_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiWbigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgtfidf_dict', models.TextField()),
                ('id_pre_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Preprocessing')),
            ],
            options={
                'db_table': 'bigramklasifikasi',
            },
        ),
    ]
