# Generated by Django 2.2.5 on 2020-10-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembobotan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata', models.CharField(max_length=100)),
                ('tf', models.DecimalField(decimal_places=4, max_digits=19)),
                ('idf', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tf_idf', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'pembobotan',
            },
        ),
    ]
