# Generated by Django 2.2.5 on 2020-10-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembobotan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembobotan',
            name='tf_idf',
        ),
    ]
