# Generated by Django 3.0.8 on 2021-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembobotan', '0002_remove_pembobotan_tf_idf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_kata', models.CharField(max_length=100)),
                ('bg_tf', models.DecimalField(decimal_places=4, max_digits=19)),
                ('bg_idf', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'bigram',
            },
        ),
    ]
